export {
  useGetGenderQuery,
  useGetInternetAccessQuery,
  useGetLanguagesQuery,
  useGetParkingQuery,
  useGetPaymentTypeQuery,
  useGetSmokingOnSiteQuery,
  useGetAdditionalServiceQuery,
  useGetFoodTypeQuery,
  useGetRoomCategoriesQuery,
  useGetObjectStarRatingQuery,
  useGetReportingDocumentTypeQuery,
  useGetBedTypesQuery,
  useGetCurrenciesQuery,
  useGetCleaningFeeTypesQuery,
  useGetMealServiceTypesQuery,
  useGetFromBookingToCheckInQuery,
  useGetInstantBookingValidQuery,
  useGetFloorTypeQuery,
  useGetRoomTypeNamesQuery,
  useGetKitchenTypeQuery,
  useGetRepairTypeQuery,
  useGetNumberOfIsolatedBedroomQuery,
} from "./model/api/commonReferenceApi.ts";
